- group: 查询类功能
  list:
    - icon: doctor
      title: "#医药查询 疾病/症状/医院/医生/药品"
      desc: 便利的医药查询功能
    - icon: cat
      title: "#cat 开始吸猫"
      desc: 猫咪图捕捉
    - icon: hot
      title: "#热搜 虎扑/知乎/36氪/百度/哔哩哔哩/贴吧/微博/抖音/豆瓣/少数派/IT资讯/微信"
      desc: 开局五子棋游戏
    - icon: computer
      title: "#电脑软件推荐"
      desc: 推荐PC软件
    - icon: android
      title: "#安卓软件推荐"
      desc: 推荐安卓软件
    - icon: buyer
      title: "#买家秀"
      desc: 淘宝买家秀
    - icon: pic1
      title: "#累了"
      desc: 疲惫往往是过度劳累
- group: 工具类合集
  list:
    - icon: translate
      title: "翻中/英/日 xxx"
      desc: 百度翻译，例如：翻中 I want it!
    - icon: 百科
      title: "#百科/wiki xxx"
      desc: 百度百科/搜狗百科
    - icon: tiktok
      title: "xxxv.douyin.com"
      desc: 抖音分享实时下载
    - icon: bilibili
      title: "bilibili/b23"
      desc: 哔哩哔哩分享实时下载
    - icon: 推特
      title: "小蓝鸟"
      desc: 推特学习版分享实时下载
    - icon: acfun
      title: "acfun"
      desc: 猴山分享实时下载
    - icon: redbook
      title: "小红书"
      desc: 小红书分享实时下载
    - icon: literature
      title: "论文"
      desc: SCI论文实时解析
- group: 其他指令
  list:
    - icon: update
      title: "#R插件更新"
      desc: "进行更新R插件"