- group: 查询类功能
  list:
    - icon: doctor
      title: "#医药查询 疾病/症状/医院/医生/药品"
      desc: 便利的医药查询功能
    - icon: cat
      title: "#cat 开始吸猫"
      desc: 猫咪图捕捉
    - icon: computer
      title: "#推荐软件"
      desc: 推荐PC、Android软件
    - icon: buyer
      title: "#买家秀"
      desc: 淘宝买家秀
    - icon: pic1
      title: "#累了"
      desc: 疲惫往往是过度劳累
    - icon: youthLearning
      title: "#青年大学习"
      desc: 青年大学习答案和截图
    - icon: searchBook
      title: "#搜书/#bookid"
      desc: 基于zli的搜书功能
    - icon: zhubai
      title: "#竹白"
      desc: 基于竹白百科的搜索
- group: 工具类合集
  list:
    - icon: translate
      title: "翻中/英/日 xxx"
      desc: 百度翻译，例如：翻中 I want it!
    - icon: 百科
      title: "#百科/wiki xxx"
      desc: 百度百科/搜狗百科
    - icon: tiktok
      title: "xxxv.douyin.com"
      desc: 抖音分享实时下载
    - icon: bilibili
      title: "bilibili/b23"
      desc: 哔哩哔哩分享实时下载
    - icon: bilimusic
      title: "bili音乐+链接"
      desc: 哔哩哔哩音乐分享实时下载
    - icon: youtube
      title: "youtube.com"
      desc: 油管学习版分享实时下载
    - icon: 推特
      title: "小蓝鸟"
      desc: 推特学习版分享实时下载
    - icon: acfun
      title: "acfun"
      desc: 猴山分享实时下载
    - icon: redbook
      title: "小红书"
      desc: 小红书分享实时下载
    - icon: kuaishou
      title: "快手（测试阶段）"
      desc: 快手分享实时下载
    - icon: literature
      title: "论文"
      desc: SCI论文实时解析
    - icon: bodian
      title: "波点音乐"
      desc: 波点云音乐点解析
    - icon: ins
      title: "Instagram"
      desc: 解析Instagram
- group: 其他指令
  list:
    - icon: update
      title: "#R插件更新"
      desc: "进行更新R插件"
    - icon: computer
      title: "【实验指令】#ocr"
      desc: "基于gpt的识图总结"