- {
  version: 1.8.1,
  data:
    [
      新增<span class="cmd">自定义识别</span>功能,
      修正<span class="cmd">油管分辨率降低到720P</span>功能,
      新增<span class="cmd">小飞机解析 Beta</span>功能,
      新增<span class="cmd">BBDown更换CDN</span>功能,
      支持<span class="cmd">锅巴</span>插件，方便查看和修改配置,
      输入<span class="cmd">#R帮助</span>获取插件帮助,
      输入<span class="cmd">#R更新</span>更新插件,
      输入<span class="cmd">#R版本</span>获取插件版本,
    ],
}
